let insightRange=7,insightMetric='water';
function insightDates(n){let out=[],end=new Date();end.setHours(12,0,0,0);let rangeStart=new Date(end);rangeStart.setDate(end.getDate()-(n-1));let medicationStart=new Date((data.settings.startDate||todayISO())+'T12:00:00'),start=medicationStart>rangeStart?medicationStart:rangeStart;if(start>end)return out;for(let x=new Date(start);x<=end;x.setDate(x.getDate()+1))out.push(localISO(x));return out}
function insightTotals(kind,dates){let key=kind==='water'?'ml':'grams',rows=data[kind]||[];return dates.map(date=>rows.filter(x=>x.date===date).reduce((a,x)=>a+(+x[key]||0),0))}
function insightStreak(values,goal){let n=0;for(let i=values.length-1;i>=0&&values[i]>=goal;i--)n++;return n}
function average(values){return values.length?values.reduce((a,x)=>a+x,0)/values.length:0}
function bowelGap(){let ds=[...new Set((data.bowelMovements||[]).map(x=>x.date))].sort();if(ds.length<2)return null;let gaps=ds.slice(1).map((d,i)=>days(ds[i],d));return average(gaps)}
function topSymptom(){let counts={};(data.symptoms||[]).forEach(e=>(e.symptoms||[]).forEach(s=>counts[s.name]=(counts[s.name]||0)+1));let top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];return top?`${top[0]} · ${top[1]}×`:'Not enough data'}
function commonSleepQuality(){let counts={};(data.sleep||[]).forEach(x=>{if(x.quality)counts[x.quality]=(counts[x.quality]||0)+1});return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'No quality pattern yet'}
function insightDateLabel(date,index,total){let interval=total<=7?1:total<=30?5:15;if(index%interval&&index!==total-1)return'';return new Date(date+'T12:00:00').toLocaleDateString(undefined,{month:'numeric',day:'numeric'})}
function insightPatterns(dates){let inRange=x=>dates.includes(x.date),fiber=(data.fiber||[]).filter(inRange),knownFiber=fiber.filter(x=>+x.amount>0),bowel=(data.bowelMovements||[]).filter(inRange),sleep=(data.sleep||[]).filter(inRange),symptoms=(data.symptoms||[]).filter(inRange),fiberAvg=knownFiber.length?average(knownFiber.map(x=>+x.amount)).toFixed(1)+' g avg':'Amounts optional',sleepAvg=sleep.length?average(sleep.map(x=>+x.hours)).toFixed(1)+' h avg':'Not enough data';return`<div class="insightPatternGrid"><div><i data-lucide="wheat"></i><b>Fiber</b><strong>${fiber.length} day${fiber.length===1?'':'s'}</strong><span>${fiberAvg}</span></div><div><i data-lucide="toilet"></i><b>Digestion</b><strong>${bowel.length} log${bowel.length===1?'':'s'}</strong><span>${bowelGap()!=null?bowelGap().toFixed(1)+' days between logs':'Keep logging for a pattern'}</span></div><div><i data-lucide="moon-star"></i><b>Sleep</b><strong>${sleepAvg}</strong><span>${commonSleepQuality()}</span></div><div><i data-lucide="activity"></i><b>Symptoms</b><strong>${symptoms.reduce((a,x)=>a+(x.symptoms?.length||0),0)} recorded</strong><span>${topSymptom()}</span></div></div>`}
function renderInsights(){let host=document.getElementById('journeyInsights');if(!host)return;let dates=insightDates(insightRange),values=insightTotals(insightMetric,dates),goal=insightMetric==='water'?+data.settings.waterGoal:+data.settings.proteinGoal,unitLabel=insightMetric==='water'?data.settings.waterUnit:'g',max=Math.max(goal,...values,1),reached=values.filter(x=>x>=goal).length,avg=average(values),streak=insightStreak(values,goal),bars=dates.map((date,i)=>{let pct=Math.max(2,Math.min(100,values[i]/max*100)),label=insightDateLabel(date,i,dates.length),fullDate=new Date(date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});return`<div class="insightBar" title="${fullDate}: ${Math.round(values[i])} ${unitLabel}"><span class="insightValue">${values[i]?Math.round(values[i]):''}</span><i style="height:${pct}%"></i><small>${label}</small></div>`}).join('');host.innerHTML=`<div class="sectionHead insightHead"><div><span class="eyebrow">YOUR PATTERNS</span><h2>Insights</h2></div><div class="insightRanges">${[7,30,90].map(n=>`<button class="${insightRange===n?'active':''}" onclick="setInsightRange(${n})">${n}D</button>`).join('')}</div></div><div class="card insightCard"><div class="insightTabs"><button class="${insightMetric==='water'?'active':''}" onclick="setInsightMetric('water')"><i data-lucide="droplets"></i>Water</button><button class="${insightMetric==='protein'?'active':''}" onclick="setInsightMetric('protein')"><i data-lucide="biceps-flexed"></i>Protein</button></div><div class="insightSummary"><div><b>${reached}/${dates.length}</b><span>Goal days</span></div><div><b>${Math.round(avg)} ${unitLabel}</b><span>Daily average</span></div><div><b>${streak}</b><span>Current streak</span></div></div><div class="insightChartWrap"><div class="insightGoal" style="bottom:${Math.min(100,goal/max*100)}%"><span>Goal ${goal} ${unitLabel}</span></div><div class="insightChart range${insightRange} ${insightRange>30?'dense':''}">${bars}</div></div></div>${insightPatterns(dates)}<p class="insightNote">Patterns summarize your own records and are not medical conclusions.</p>`;requestAnimationFrame(()=>{window.lucide?.createIcons();let wrap=host.querySelector('.insightChartWrap');if(wrap)wrap.scrollLeft=wrap.scrollWidth})}
function setInsightRange(n){insightRange=n;renderInsights()}
function setInsightMetric(kind){insightMetric=kind;renderInsights()}
const journeyWithInsights=renderJourney;
renderJourney=function(){journeyWithInsights();let actions=document.querySelector('#journeyContent .journeyActions');if(actions&&!document.getElementById('journeyInsights'))actions.insertAdjacentHTML('afterend','<section id="journeyInsights"></section>');renderInsights()};
renderJourney();
