import {VERSION,now,today,money,major,coverageStatus,status,get,validateState} from './domain.js?release=12';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function download(data,name,type='application/octet-stream'){const url=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export function csv(rows){if(!rows.length)return'';const keys=Object.keys(rows[0]);const cell=v=>'"'+String(v??'').replace(/^[=+@\t\r]/,"'$&").replace(/^-(?!\d+(\.\d+)?$)/,"'-").replace(/"/g,'""')+'"';return '\ufeff'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n')}
export function parseCSV(text){text=text.replace(/^\ufeff/,'');const rows=[];let row=[],value='',quoted=false;for(let n=0;n<text.length;n++){const c=text[n];if(c==='"'){if(quoted&&text[n+1]==='"'){value+='"';n++}else quoted=!quoted}else if(c===','&&!quoted){row.push(value);value=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[n+1]==='\n')n++;row.push(value);if(row.some(Boolean))rows.push(row);row=[];value=''}else value+=c}if(quoted)throw Error('Unclosed quoted field in CSV.');row.push(value);if(row.some(Boolean))rows.push(row);if(rows.length<2)throw Error('CSV needs a header and at least one record.');const headers=rows.shift().map(x=>x.trim());if(new Set(headers).size!==headers.length)throw Error('Duplicate column headings.');return rows.map((r,n)=>{if(r.length!==headers.length)throw Error(`Row ${n+2}: wrong number of columns.`);return Object.fromEntries(headers.map((h,i)=>[h,r[i]]))})}
export function exportRows(s,type){if(type==='status')return s.clients.filter(c=>c.active).map(c=>{const st=coverageStatus(s,c);return {client_id:c.clientId,paid_through:st.paidThrough,status:st.status,confirmed_date:st.confirmedDate,client_name:c.name,access_expiry:c.expiry||''}});if(type==='clients')return s.clients.map(c=>({client_id:c.clientId,company_name:c.name,contact:c.contact,email:c.email,phone:c.phone,address:c.address,country:c.country,language:c.language,active:c.active,paid_through:c.paidThrough,access_expiry:c.expiry,notes:c.notes}));if(type==='services')return s.services.map(x=>({name:x.name,description:x.description,price:major(x.price,x.currency),currency:x.currency,frequency:x.frequency,duration:x.duration,active:x.active}));if(type==='invoices')return s.invoices.map(i=>({invoice_number:i.number||'Draft',client_id:get(s,'clients',i.clientId)?.clientId,profile:get(s,'profiles',i.profileId)?.name,date:i.date,due_date:i.due,period_start:i.periodStart,period_end:i.periodEnd,currency:i.currency,total:major(i.total,i.currency),status:status(s,i)}));if(type==='payments')return s.payments.map(p=>({payment_id:p.id,date:p.date,client_id:get(s,'clients',p.clientId)?.clientId,invoice_number:get(s,'invoices',p.invoiceId)?.number,amount:major(p.amount,p.currency),currency:p.currency,bank:get(s,'banks',p.bankId)?.nickname,reference:p.reference,notes:p.notes,voided_at:p.voidedAt||''}));if(type==='recurring')return s.recurring.map(r=>({client_id:get(s,'clients',r.clientId)?.clientId,profile:get(s,'profiles',r.profileId)?.name,service:get(s,'services',r.serviceId)?.name,frequency:r.frequency,amount:major(r.amount,r.currency),currency:r.currency,period_start:r.periodStart,period_end:r.periodEnd,next_generation:r.nextDate,paid_through:r.paidThrough,access_expiry:r.expiry,active:r.active}));return[]}
export async function checksum(text){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(v=>v.toString(16).padStart(2,'0')).join('')}
export async function backupEnvelope(s){return {app:'iSingil',version:VERSION,schema:1,exportedAt:now(),checksum:await checksum(JSON.stringify(s)),data:s}}
export async function validateBackup(text){let b;try{b=JSON.parse(text)}catch{throw Error('This file is not valid JSON.')}if(b.app!=='iSingil'||b.schema!==1||!b.exportedAt)throw Error('Unsupported backup.');if(await checksum(JSON.stringify(b.data))!==b.checksum)throw Error('Backup checksum does not match. File may be damaged.');validateState(b.data);return b}
export const backupName=()=>`iSingil_Backup_${today()}_${new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()).replace(':','')}.json`;
export {labels,label,bankLines,invoiceHTML} from './invoice-template.js?release=12';
import {renderInvoicePDF} from './invoice-template.js?release=12';
let libs,fontBytes;
function script(src){return new Promise((resolve,reject)=>{const el=document.createElement('script');el.src=src;el.onload=resolve;el.onerror=()=>reject(Error('Document tools could not load. Open the app online once to cache them.'));document.head.append(el)})}
async function loadPDF(){if(window.PDFLib&&window.fontkit&&window.JSZip)libs=Promise.resolve();if(!libs)libs=Promise.all([script('./vendor/pdf-lib.min.js'),script('./vendor/fontkit.umd.min.js'),script('./vendor/jszip.min.js')]).catch(e=>{libs=null;throw e});await libs;if(!fontBytes){const r=await fetch('./vendor/NotoSansJP.ttf');if(!r.ok)throw Error('Invoice font could not load.');fontBytes=await r.arrayBuffer()}}
export async function invoicePDF(i){await loadPDF();return renderInvoicePDF(i,window.PDFLib,window.fontkit,fontBytes)}
export async function archive(s){await loadPDF();const zip=new window.JSZip();const envelope=await backupEnvelope(s);zip.file(backupName(),JSON.stringify(envelope,null,2));const manifest=[];for(const type of ['clients','invoices','payments','recurring','status']){const data=csv(exportRows(s,type));zip.file(`exports/${type}.csv`,data)}for(const i of s.invoices.filter(i=>i.state!=='Draft')){const file=`invoices/${i.number.replace(/[^a-z0-9_-]/gi,'_')}_${i.id.slice(0,8)}.pdf`;const bytes=await invoicePDF(i);zip.file(file,bytes);manifest.push({file,invoiceId:i.id,number:i.number})}zip.file('manifest.json',JSON.stringify({app:'iSingil',version:VERSION,exportedAt:now(),backupChecksum:envelope.checksum,invoices:manifest},null,2));return zip.generateAsync({type:'blob',compression:'DEFLATE'})}
